// Auto-generated types from OpenAPI specification
// Do not edit manually

use serde::{Deserialize, Serialize};

// From: get_domains_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomains200ResponseInner {
    /// The ID of the domain
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the domain
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the team
    #[serde(rename = "teamId")]
    pub team_id: String,
    /// The status of the domain
    #[serde(rename = "status")]
    pub status: String,
    /// The region of the domain
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Whether click tracking is enabled
    #[serde(rename = "clickTracking", skip_serializing_if = "Option::is_none")]
    pub click_tracking: Option<bool>,
    /// Whether open tracking is enabled
    #[serde(rename = "openTracking", skip_serializing_if = "Option::is_none")]
    pub open_tracking: Option<bool>,
    /// The public key of the domain
    #[serde(rename = "publicKey")]
    pub public_key: String,
    /// The DKIM status of the domain
    #[serde(rename = "dkimStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dkim_status: Option<Option<String>>,
    /// The SPF details of the domain
    #[serde(rename = "spfDetails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spf_details: Option<Option<String>>,
    /// The creation date of the domain
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The last update date of the domain
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// Whether DMARC is added
    #[serde(rename = "dmarcAdded", skip_serializing_if = "Option::is_none")]
    pub dmarc_added: Option<bool>,
    /// Whether the domain is verifying
    #[serde(rename = "isVerifying", skip_serializing_if = "Option::is_none")]
    pub is_verifying: Option<bool>,
    /// The error message of the domain
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    /// The subdomain of the domain
    #[serde(rename = "subdomain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subdomain: Option<Option<String>>,
    /// The verification error of the domain
    #[serde(rename = "verificationError", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_error: Option<Option<String>>,
    /// The last checked time of the domain
    #[serde(rename = "lastCheckedTime", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_checked_time: Option<Option<String>>,
    /// The DNS records of the domain
    #[serde(rename = "dnsRecords")]
    pub dns_records: Vec<GetDomains200ResponseInnerDnsRecordsInner>,
}

impl GetDomains200ResponseInner {
    pub fn new(id: String, name: String, team_id: String, status: String, public_key: String, created_at: String, updated_at: String, dns_records: Vec<GetDomains200ResponseInnerDnsRecordsInner>) -> GetDomains200ResponseInner {
        GetDomains200ResponseInner {
            id,
            name,
            team_id,
            status,
            region: None,
            click_tracking: None,
            open_tracking: None,
            public_key,
            dkim_status: None,
            spf_details: None,
            created_at,
            updated_at,
            dmarc_added: None,
            is_verifying: None,
            error_message: None,
            subdomain: None,
            verification_error: None,
            last_checked_time: None,
            dns_records,
        }
    }
}


// From: get_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContactBook200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji")]
    pub emoji: String,
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<serde_json::Value>>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "details")]
    pub details: Box<GetContactBook200ResponseDetails>,
}

impl GetContactBook200Response {
    pub fn new(id: String, name: String, emoji: String, team_id: String, created_at: String, updated_at: String, details: GetContactBook200ResponseDetails) -> GetContactBook200Response {
        GetContactBook200Response {
            id,
            name,
            emoji,
            properties: None,
            team_id,
            created_at,
            updated_at,
            details: Box::new(details),
        }
    }
}


// From: get_campaigns_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCampaigns200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "sent", skip_serializing_if = "Option::is_none")]
    pub sent: Option<f64>,
    #[serde(rename = "delivered", skip_serializing_if = "Option::is_none")]
    pub delivered: Option<f64>,
    #[serde(rename = "opened", skip_serializing_if = "Option::is_none")]
    pub opened: Option<f64>,
    #[serde(rename = "clicked", skip_serializing_if = "Option::is_none")]
    pub clicked: Option<f64>,
}

impl GetCampaigns200ResponseInner {
    pub fn new(id: String, name: String, subject: String, created_at: String) -> GetCampaigns200ResponseInner {
        GetCampaigns200ResponseInner {
            id,
            name,
            subject,
            status: None,
            created_at,
            sent: None,
            delivered: None,
            opened: None,
            clicked: None,
        }
    }
}


// From: create_campaign_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCampaign200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "previewText", deserialize_with = "Option::deserialize")]
    pub preview_text: Option<String>,
    #[serde(rename = "contactBookId", deserialize_with = "Option::deserialize")]
    pub contact_book_id: Option<String>,
    #[serde(rename = "html", deserialize_with = "Option::deserialize")]
    pub html: Option<String>,
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "scheduledAt", deserialize_with = "Option::deserialize")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "batchSize")]
    pub batch_size: i32,
    #[serde(rename = "batchWindowMinutes")]
    pub batch_window_minutes: i32,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "sent")]
    pub sent: i32,
    #[serde(rename = "delivered")]
    pub delivered: i32,
    #[serde(rename = "opened")]
    pub opened: i32,
    #[serde(rename = "clicked")]
    pub clicked: i32,
    #[serde(rename = "unsubscribed")]
    pub unsubscribed: i32,
    #[serde(rename = "bounced")]
    pub bounced: i32,
    #[serde(rename = "hardBounced")]
    pub hard_bounced: i32,
    #[serde(rename = "complained")]
    pub complained: i32,
    #[serde(rename = "replyTo")]
    pub reply_to: Vec<String>,
    #[serde(rename = "cc")]
    pub cc: Vec<String>,
    #[serde(rename = "bcc")]
    pub bcc: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl CreateCampaign200Response {
    pub fn new(id: String, name: String, from: String, subject: String, preview_text: Option<String>, contact_book_id: Option<String>, html: Option<String>, content: Option<String>, status: String, scheduled_at: Option<String>, batch_size: i32, batch_window_minutes: i32, total: i32, sent: i32, delivered: i32, opened: i32, clicked: i32, unsubscribed: i32, bounced: i32, hard_bounced: i32, complained: i32, reply_to: Vec<String>, cc: Vec<String>, bcc: Vec<String>, created_at: String, updated_at: String) -> CreateCampaign200Response {
        CreateCampaign200Response {
            id,
            name,
            from,
            subject,
            preview_text,
            contact_book_id,
            html,
            content,
            status,
            scheduled_at,
            batch_size,
            batch_window_minutes,
            total,
            sent,
            delivered,
            opened,
            clicked,
            unsubscribed,
            bounced,
            hard_bounced,
            complained,
            reply_to,
            cc,
            bcc,
            created_at,
            updated_at,
        }
    }
}


// From: create_campaign_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCampaignRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "previewText", skip_serializing_if = "Option::is_none")]
    pub preview_text: Option<String>,
    #[serde(rename = "contactBookId")]
    pub contact_book_id: String,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "replyTo", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<serde_json::Value>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<serde_json::Value>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<serde_json::Value>,
    #[serde(rename = "sendNow", skip_serializing_if = "Option::is_none")]
    pub send_now: Option<bool>,
    /// Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "batchSize", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i32>,
}

impl CreateCampaignRequest {
    pub fn new(name: String, from: String, subject: String, contact_book_id: String) -> CreateCampaignRequest {
        CreateCampaignRequest {
            name,
            from,
            subject,
            preview_text: None,
            contact_book_id,
            content: None,
            html: None,
            reply_to: None,
            cc: None,
            bcc: None,
            send_now: None,
            scheduled_at: None,
            batch_size: None,
        }
    }
}


// From: create_template_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTemplate200Response {
    #[serde(rename = "id")]
    pub id: String,
}

impl CreateTemplate200Response {
    pub fn new(id: String) -> CreateTemplate200Response {
        CreateTemplate200Response {
            id,
        }
    }
}


// From: update_contact_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContactRequest {
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "subscribed", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
}

impl UpdateContactRequest {
    pub fn new() -> UpdateContactRequest {
        UpdateContactRequest {
            first_name: None,
            last_name: None,
            properties: None,
            subscribed: None,
        }
    }
}


// From: add_suppression_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddSuppressionRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "reason")]
    pub reason: Reason,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl AddSuppressionRequest {
    pub fn new(email: String, reason: Reason) -> AddSuppressionRequest {
        AddSuppressionRequest {
            email,
            reason,
            source: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "HARD_BOUNCE")]
    HardBounce,
    #[serde(rename = "COMPLAINT")]
    Complaint,
    #[serde(rename = "MANUAL")]
    Manual,
    #[serde(rename = "UNSUBSCRIBE")]
    Unsubscribe,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::HardBounce
    }
}


// From: get_domains_200_response_inner_dns_records_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomains200ResponseInnerDnsRecordsInner {
    /// DNS record type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// DNS record name
    #[serde(rename = "name")]
    pub name: String,
    /// DNS record value
    #[serde(rename = "value")]
    pub value: String,
    /// DNS record TTL
    #[serde(rename = "ttl")]
    pub ttl: String,
    /// DNS record priority
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<String>>,
    /// The status of the domain
    #[serde(rename = "status")]
    pub status: String,
    /// Whether the record is recommended
    #[serde(rename = "recommended", skip_serializing_if = "Option::is_none")]
    pub recommended: Option<bool>,
}

impl GetDomains200ResponseInnerDnsRecordsInner {
    pub fn new(r#type: Type, name: String, value: String, ttl: String, status: String) -> GetDomains200ResponseInnerDnsRecordsInner {
        GetDomains200ResponseInnerDnsRecordsInner {
            r#type,
            name,
            value,
            ttl,
            priority: None,
            status,
            recommended: None,
        }
    }
}
/// DNS record type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "TXT")]
    Txt,
}

impl Default for Type {
    fn default() -> Type {
        Self::Mx
    }
}


// From: get_health_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHealth200Response {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "uptime")]
    pub uptime: f64,
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
}

impl GetHealth200Response {
    pub fn new(status: String, uptime: f64, timestamp: f64) -> GetHealth200Response {
        GetHealth200Response {
            status,
            uptime,
            timestamp,
        }
    }
}


// From: create_contact_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContact200Response {
    #[serde(rename = "contactId", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
}

impl CreateContact200Response {
    pub fn new() -> CreateContact200Response {
        CreateContact200Response {
            contact_id: None,
        }
    }
}


// From: schedule_campaign_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleCampaignRequest {
    /// Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "batchSize", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i32>,
}

impl ScheduleCampaignRequest {
    pub fn new() -> ScheduleCampaignRequest {
        ScheduleCampaignRequest {
            scheduled_at: None,
            batch_size: None,
        }
    }
}


// From: list_emails_domain_id_parameter.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEmailsDomainIdParameter {
}

impl ListEmailsDomainIdParameter {
    pub fn new() -> ListEmailsDomainIdParameter {
        ListEmailsDomainIdParameter {
        }
    }
}


// From: update_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContactBook200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateContactBook200Response {
    pub fn new(id: String, name: String) -> UpdateContactBook200Response {
        UpdateContactBook200Response {
            id,
            name,
        }
    }
}


// From: delete_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteContactBook200Response {
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteContactBook200Response {
    pub fn new(success: bool) -> DeleteContactBook200Response {
        DeleteContactBook200Response {
            success,
        }
    }
}


// From: update_contact_book_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContactBookRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl UpdateContactBookRequest {
    pub fn new() -> UpdateContactBookRequest {
        UpdateContactBookRequest {
            name: None,
            emoji: None,
            properties: None,
        }
    }
}


// From: get_api_keys_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKeys200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partialToken")]
    pub partial_token: String,
    #[serde(rename = "lastUsed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_used: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "permission")]
    pub permission: String,
}

impl GetApiKeys200ResponseInner {
    pub fn new(id: String, name: String, partial_token: String, created_at: String, permission: String) -> GetApiKeys200ResponseInner {
        GetApiKeys200ResponseInner {
            id,
            name,
            partial_token,
            last_used: None,
            created_at,
            permission,
        }
    }
}


// From: create_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContactBook200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji")]
    pub emoji: String,
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<serde_json::Value>>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl CreateContactBook200Response {
    pub fn new(id: String, name: String, emoji: String, team_id: String, created_at: String, updated_at: String) -> CreateContactBook200Response {
        CreateContactBook200Response {
            id,
            name,
            emoji,
            properties: None,
            team_id,
            created_at,
            updated_at,
        }
    }
}


// From: create_campaign_request_reply_to.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCampaignRequestReplyTo {
}

impl CreateCampaignRequestReplyTo {
    pub fn new() -> CreateCampaignRequestReplyTo {
        CreateCampaignRequestReplyTo {
        }
    }
}


// From: get_templates_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTemplates200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "html", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub html: Option<Option<String>>,
    #[serde(rename = "content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GetTemplates200ResponseInner {
    pub fn new(id: String, name: String, subject: String, team_id: String, created_at: String, updated_at: String) -> GetTemplates200ResponseInner {
        GetTemplates200ResponseInner {
            id,
            name,
            subject,
            html: None,
            content: None,
            team_id,
            created_at,
            updated_at,
        }
    }
}


// From: create_template_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTemplateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl CreateTemplateRequest {
    pub fn new(name: String, subject: String) -> CreateTemplateRequest {
        CreateTemplateRequest {
            name,
            subject,
            html: None,
            content: None,
        }
    }
}


// From: create_domain_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDomainRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "region")]
    pub region: String,
}

impl CreateDomainRequest {
    pub fn new(name: String, region: String) -> CreateDomainRequest {
        CreateDomainRequest {
            name,
            region,
        }
    }
}


// From: get_contact_book_200_response_details.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContactBook200ResponseDetails {
    #[serde(rename = "totalContacts")]
    pub total_contacts: f64,
    #[serde(rename = "unsubscribedContacts")]
    pub unsubscribed_contacts: f64,
    #[serde(rename = "campaigns")]
    pub campaigns: Vec<serde_json::Value>,
}

impl GetContactBook200ResponseDetails {
    pub fn new(total_contacts: f64, unsubscribed_contacts: f64, campaigns: Vec<serde_json::Value>) -> GetContactBook200ResponseDetails {
        GetContactBook200ResponseDetails {
            total_contacts,
            unsubscribed_contacts,
            campaigns,
        }
    }
}


// From: create_contact_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContactRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "subscribed", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
}

impl CreateContactRequest {
    pub fn new(email: String) -> CreateContactRequest {
        CreateContactRequest {
            email,
            first_name: None,
            last_name: None,
            properties: None,
            subscribed: None,
        }
    }
}


// From: send_email_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendEmailRequest {
    #[serde(rename = "to")]
    pub to: serde_json::Value,
    #[serde(rename = "from")]
    pub from: String,
    /// Optional when templateId is provided
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// ID of a template from the dashboard
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "replyTo", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<serde_json::Value>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<serde_json::Value>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<serde_json::Value>,
    #[serde(rename = "text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text: Option<Option<String>>,
    #[serde(rename = "html", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub html: Option<Option<String>>,
    /// Custom headers to included with the emails
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<serde_json::Value>>,
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "inReplyToId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_reply_to_id: Option<Option<String>>,
}

impl SendEmailRequest {
    pub fn new(to: serde_json::Value, from: String) -> SendEmailRequest {
        SendEmailRequest {
            to: to,
            from,
            subject: None,
            template_id: None,
            variables: None,
            reply_to: None,
            cc: None,
            bcc: None,
            text: None,
            html: None,
            headers: None,
            attachments: None,
            scheduled_at: None,
            in_reply_to_id: None,
        }
    }
}


// From: create_contact_book_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContactBookRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl CreateContactBookRequest {
    pub fn new(name: String) -> CreateContactBookRequest {
        CreateContactBookRequest {
            name,
            emoji: None,
            properties: None,
        }
    }
}


// From: create_api_key_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeyRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Permission>,
}

impl CreateApiKeyRequest {
    pub fn new(name: String) -> CreateApiKeyRequest {
        CreateApiKeyRequest {
            name,
            permission: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permission {
    #[serde(rename = "FULL")]
    Full,
    #[serde(rename = "SENDING")]
    Sending,
}

impl Default for Permission {
    fn default() -> Permission {
        Self::Full
    }
}


// From: send_email_request_to.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendEmailRequestTo {
}

impl SendEmailRequestTo {
    pub fn new() -> SendEmailRequestTo {
        SendEmailRequestTo {
        }
    }
}


// From: update_template_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTemplateRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl UpdateTemplateRequest {
    pub fn new() -> UpdateTemplateRequest {
        UpdateTemplateRequest {
            name: None,
            subject: None,
            html: None,
            content: None,
        }
    }
}


