// Auto-generated types from OpenAPI specification
// Do not edit manually

use serde::{Deserialize, Serialize};

// From: add_domain_route_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddDomainRouteRequest {
    #[serde(rename = "providerConnectionId")]
    pub provider_connection_id: uuid::Uuid,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
}

impl AddDomainRouteRequest {
    pub fn new(provider_connection_id: uuid::Uuid) -> AddDomainRouteRequest {
        AddDomainRouteRequest {
            provider_connection_id,
            weight: None,
        }
    }
}

// From: add_suppression_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddSuppression200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "source", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub source: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl AddSuppression200Response {
    pub fn new(id: String, email: String, reason: String, created_at: String) -> AddSuppression200Response {
        AddSuppression200Response {
            id,
            email,
            reason,
            source: None,
            created_at,
        }
    }
}

// From: add_suppression_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddSuppressionRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "reason")]
    pub reason: Reason,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl AddSuppressionRequest {
    pub fn new(email: String, reason: Reason) -> AddSuppressionRequest {
        AddSuppressionRequest {
            email,
            reason,
            source: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "HARD_BOUNCE")]
    HardBounce,
    #[serde(rename = "COMPLAINT")]
    Complaint,
    #[serde(rename = "MANUAL")]
    Manual,
    #[serde(rename = "UNSUBSCRIBE")]
    Unsubscribe,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::HardBounce
    }
}

// From: create_api_key_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKey200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl CreateApiKey200Response {
    pub fn new(id: String, token: String) -> CreateApiKey200Response {
        CreateApiKey200Response {
            id,
            token,
        }
    }
}

// From: create_api_key_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeyRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Permission>,
}

impl CreateApiKeyRequest {
    pub fn new(name: String) -> CreateApiKeyRequest {
        CreateApiKeyRequest {
            name,
            permission: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permission {
    #[serde(rename = "FULL")]
    Full,
    #[serde(rename = "SENDING")]
    Sending,
}

impl Default for Permission {
    fn default() -> Permission {
        Self::Full
    }
}

// From: create_campaign_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCampaign200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "previewText", deserialize_with = "Option::deserialize")]
    pub preview_text: Option<String>,
    #[serde(rename = "contactBookId", deserialize_with = "Option::deserialize")]
    pub contact_book_id: Option<String>,
    #[serde(rename = "html", deserialize_with = "Option::deserialize")]
    pub html: Option<String>,
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "scheduledAt", deserialize_with = "Option::deserialize")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "batchSize")]
    pub batch_size: i32,
    #[serde(rename = "batchWindowMinutes")]
    pub batch_window_minutes: i32,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "sent")]
    pub sent: i32,
    #[serde(rename = "delivered")]
    pub delivered: i32,
    #[serde(rename = "opened")]
    pub opened: i32,
    #[serde(rename = "clicked")]
    pub clicked: i32,
    #[serde(rename = "unsubscribed")]
    pub unsubscribed: i32,
    #[serde(rename = "bounced")]
    pub bounced: i32,
    #[serde(rename = "hardBounced")]
    pub hard_bounced: i32,
    #[serde(rename = "complained")]
    pub complained: i32,
    #[serde(rename = "replyTo")]
    pub reply_to: Vec<String>,
    #[serde(rename = "cc")]
    pub cc: Vec<String>,
    #[serde(rename = "bcc")]
    pub bcc: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl CreateCampaign200Response {
    pub fn new(id: String, name: String, from: String, subject: String, preview_text: Option<String>, contact_book_id: Option<String>, html: Option<String>, content: Option<String>, status: String, scheduled_at: Option<String>, batch_size: i32, batch_window_minutes: i32, total: i32, sent: i32, delivered: i32, opened: i32, clicked: i32, unsubscribed: i32, bounced: i32, hard_bounced: i32, complained: i32, reply_to: Vec<String>, cc: Vec<String>, bcc: Vec<String>, created_at: String, updated_at: String) -> CreateCampaign200Response {
        CreateCampaign200Response {
            id,
            name,
            from,
            subject,
            preview_text,
            contact_book_id,
            html,
            content,
            status,
            scheduled_at,
            batch_size,
            batch_window_minutes,
            total,
            sent,
            delivered,
            opened,
            clicked,
            unsubscribed,
            bounced,
            hard_bounced,
            complained,
            reply_to,
            cc,
            bcc,
            created_at,
            updated_at,
        }
    }
}

// From: create_campaign_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCampaignRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "previewText", skip_serializing_if = "Option::is_none")]
    pub preview_text: Option<String>,
    #[serde(rename = "contactBookId")]
    pub contact_book_id: String,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "replyTo", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<serde_json::Value>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<serde_json::Value>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<serde_json::Value>,
    #[serde(rename = "sendNow", skip_serializing_if = "Option::is_none")]
    pub send_now: Option<bool>,
    /// Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "batchSize", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i32>,
}

impl CreateCampaignRequest {
    pub fn new(name: String, from: String, subject: String, contact_book_id: String) -> CreateCampaignRequest {
        CreateCampaignRequest {
            name,
            from,
            subject,
            preview_text: None,
            contact_book_id,
            content: None,
            html: None,
            reply_to: None,
            cc: None,
            bcc: None,
            send_now: None,
            scheduled_at: None,
            batch_size: None,
        }
    }
}

// From: create_campaign_request_reply_to.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCampaignRequestReplyTo {
}

impl CreateCampaignRequestReplyTo {
    pub fn new() -> CreateCampaignRequestReplyTo {
        CreateCampaignRequestReplyTo {
        }
    }
}

// From: create_contact_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContact200Response {
    #[serde(rename = "contactId", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<String>,
}

impl CreateContact200Response {
    pub fn new() -> CreateContact200Response {
        CreateContact200Response {
            contact_id: None,
        }
    }
}

// From: create_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContactBook200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji")]
    pub emoji: String,
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<serde_json::Value>>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl CreateContactBook200Response {
    pub fn new(id: String, name: String, emoji: String, team_id: String, created_at: String, updated_at: String) -> CreateContactBook200Response {
        CreateContactBook200Response {
            id,
            name,
            emoji,
            properties: None,
            team_id,
            created_at,
            updated_at,
        }
    }
}

// From: create_contact_book_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContactBookRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl CreateContactBookRequest {
    pub fn new(name: String) -> CreateContactBookRequest {
        CreateContactBookRequest {
            name,
            emoji: None,
            properties: None,
        }
    }
}

// From: create_contact_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContactRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "subscribed", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
}

impl CreateContactRequest {
    pub fn new(email: String) -> CreateContactRequest {
        CreateContactRequest {
            email,
            first_name: None,
            last_name: None,
            properties: None,
            subscribed: None,
        }
    }
}

// From: create_domain_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDomainRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "providerConnectionId")]
    pub provider_connection_id: uuid::Uuid,
}

impl CreateDomainRequest {
    pub fn new(name: String, provider_connection_id: uuid::Uuid) -> CreateDomainRequest {
        CreateDomainRequest {
            name,
            provider_connection_id,
        }
    }
}

// From: create_provider_connection_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProviderConnectionRequest {
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "credentials")]
    pub credentials: Box<CreateProviderConnectionRequestCredentials>,
}

impl CreateProviderConnectionRequest {
    pub fn new(provider: Provider, name: String, credentials: CreateProviderConnectionRequestCredentials) -> CreateProviderConnectionRequest {
        CreateProviderConnectionRequest {
            provider,
            name,
            credentials: Box::new(credentials),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "ses")]
    Ses,
    #[serde(rename = "sendgrid")]
    Sendgrid,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Ses
    }
}

// From: create_provider_connection_request_credentials.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProviderConnectionRequestCredentials {
    #[serde(rename = "accessKeyId", skip_serializing_if = "Option::is_none")]
    pub access_key_id: Option<String>,
    #[serde(rename = "secretAccessKey", skip_serializing_if = "Option::is_none")]
    pub secret_access_key: Option<String>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
}

impl CreateProviderConnectionRequestCredentials {
    pub fn new() -> CreateProviderConnectionRequestCredentials {
        CreateProviderConnectionRequestCredentials {
            access_key_id: None,
            secret_access_key: None,
            region: None,
            api_key: None,
        }
    }
}

// From: create_template_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTemplate200Response {
    #[serde(rename = "id")]
    pub id: String,
}

impl CreateTemplate200Response {
    pub fn new(id: String) -> CreateTemplate200Response {
        CreateTemplate200Response {
            id,
        }
    }
}

// From: create_template_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTemplateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl CreateTemplateRequest {
    pub fn new(name: String, subject: String) -> CreateTemplateRequest {
        CreateTemplateRequest {
            name,
            subject,
            html: None,
            content: None,
        }
    }
}

// From: create_webhook_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<EventTypes>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl CreateWebhookRequest {
    pub fn new(url: String, event_types: Vec<EventTypes>) -> CreateWebhookRequest {
        CreateWebhookRequest {
            url,
            description: None,
            event_types,
            secret: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventTypes {
    #[serde(rename = "contact.created")]
    ContactCreated,
    #[serde(rename = "contact.updated")]
    ContactUpdated,
    #[serde(rename = "contact.deleted")]
    ContactDeleted,
    #[serde(rename = "domain.created")]
    DomainCreated,
    #[serde(rename = "domain.verified")]
    DomainVerified,
    #[serde(rename = "domain.updated")]
    DomainUpdated,
    #[serde(rename = "domain.deleted")]
    DomainDeleted,
    #[serde(rename = "email.queued")]
    EmailQueued,
    #[serde(rename = "email.sent")]
    EmailSent,
    #[serde(rename = "email.delivery_delayed")]
    EmailDeliveryDelayed,
    #[serde(rename = "email.delivered")]
    EmailDelivered,
    #[serde(rename = "email.bounced")]
    EmailBounced,
    #[serde(rename = "email.rejected")]
    EmailRejected,
    #[serde(rename = "email.rendering_failure")]
    EmailRenderingFailure,
    #[serde(rename = "email.complained")]
    EmailComplained,
    #[serde(rename = "email.failed")]
    EmailFailed,
    #[serde(rename = "email.cancelled")]
    EmailCancelled,
    #[serde(rename = "email.suppressed")]
    EmailSuppressed,
    #[serde(rename = "email.opened")]
    EmailOpened,
    #[serde(rename = "email.clicked")]
    EmailClicked,
}

impl Default for EventTypes {
    fn default() -> EventTypes {
        Self::ContactCreated
    }
}

// From: delete_webhook_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteWebhook200Response {
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteWebhook200Response {
    pub fn new(success: bool) -> DeleteWebhook200Response {
        DeleteWebhook200Response {
            success,
        }
    }
}

// From: error.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


/// Error : Error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "docs", skip_serializing_if = "Option::is_none")]
    pub docs: Option<String>,
}

impl Error {
    /// Error response
    pub fn new(code: String, message: String) -> Error {
        Error {
            code,
            message,
            docs: None,
        }
    }
}

// From: get_analytics_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnalytics200Response {
    #[serde(rename = "day")]
    pub day: Vec<GetAnalytics200ResponseDayInner>,
    #[serde(rename = "month")]
    pub month: Vec<GetAnalytics200ResponseDayInner>,
}

impl GetAnalytics200Response {
    pub fn new(day: Vec<GetAnalytics200ResponseDayInner>, month: Vec<GetAnalytics200ResponseDayInner>) -> GetAnalytics200Response {
        GetAnalytics200Response {
            day,
            month,
        }
    }
}

// From: get_analytics_200_response_day_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnalytics200ResponseDayInner {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "sent")]
    pub sent: f64,
}

impl GetAnalytics200ResponseDayInner {
    pub fn new(r#type: String, sent: f64) -> GetAnalytics200ResponseDayInner {
        GetAnalytics200ResponseDayInner {
            r#type,
            sent,
        }
    }
}

// From: get_api_keys_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApiKeys200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partialToken")]
    pub partial_token: String,
    #[serde(rename = "lastUsed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_used: Option<Option<String>>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "permission")]
    pub permission: String,
}

impl GetApiKeys200ResponseInner {
    pub fn new(id: String, name: String, partial_token: String, created_at: String, permission: String) -> GetApiKeys200ResponseInner {
        GetApiKeys200ResponseInner {
            id,
            name,
            partial_token,
            last_used: None,
            created_at,
            permission,
        }
    }
}

// From: get_campaigns_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCampaigns200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "sent", skip_serializing_if = "Option::is_none")]
    pub sent: Option<f64>,
    #[serde(rename = "delivered", skip_serializing_if = "Option::is_none")]
    pub delivered: Option<f64>,
    #[serde(rename = "opened", skip_serializing_if = "Option::is_none")]
    pub opened: Option<f64>,
    #[serde(rename = "clicked", skip_serializing_if = "Option::is_none")]
    pub clicked: Option<f64>,
}

impl GetCampaigns200ResponseInner {
    pub fn new(id: String, name: String, subject: String, created_at: String) -> GetCampaigns200ResponseInner {
        GetCampaigns200ResponseInner {
            id,
            name,
            subject,
            status: None,
            created_at,
            sent: None,
            delivered: None,
            opened: None,
            clicked: None,
        }
    }
}

// From: get_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContactBook200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji")]
    pub emoji: String,
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<serde_json::Value>>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "details")]
    pub details: Box<GetContactBook200ResponseDetails>,
}

impl GetContactBook200Response {
    pub fn new(id: String, name: String, emoji: String, team_id: String, created_at: String, updated_at: String, details: GetContactBook200ResponseDetails) -> GetContactBook200Response {
        GetContactBook200Response {
            id,
            name,
            emoji,
            properties: None,
            team_id,
            created_at,
            updated_at,
            details: Box::new(details),
        }
    }
}

// From: get_contact_book_200_response_details.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContactBook200ResponseDetails {
    #[serde(rename = "totalContacts")]
    pub total_contacts: f64,
    #[serde(rename = "unsubscribedContacts")]
    pub unsubscribed_contacts: f64,
    #[serde(rename = "campaigns")]
    pub campaigns: Vec<serde_json::Value>,
}

impl GetContactBook200ResponseDetails {
    pub fn new(total_contacts: f64, unsubscribed_contacts: f64, campaigns: Vec<serde_json::Value>) -> GetContactBook200ResponseDetails {
        GetContactBook200ResponseDetails {
            total_contacts,
            unsubscribed_contacts,
            campaigns,
        }
    }
}

// From: get_domain_analytics_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomainAnalytics200ResponseInner {
    /// The date of the analytics
    #[serde(rename = "date")]
    pub date: String,
    /// Number of emails sent
    #[serde(rename = "sent")]
    pub sent: f64,
    /// Number of emails delivered
    #[serde(rename = "delivered")]
    pub delivered: f64,
    /// Number of emails opened
    #[serde(rename = "opened")]
    pub opened: f64,
    /// Number of emails clicked
    #[serde(rename = "clicked")]
    pub clicked: f64,
    /// Number of emails bounced
    #[serde(rename = "bounced")]
    pub bounced: f64,
    /// Number of emails complained
    #[serde(rename = "complained")]
    pub complained: f64,
}

impl GetDomainAnalytics200ResponseInner {
    pub fn new(date: String, sent: f64, delivered: f64, opened: f64, clicked: f64, bounced: f64, complained: f64) -> GetDomainAnalytics200ResponseInner {
        GetDomainAnalytics200ResponseInner {
            date,
            sent,
            delivered,
            opened,
            clicked,
            bounced,
            complained,
        }
    }
}

// From: get_domain_stats_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomainStats200Response {
    /// Total emails sent
    #[serde(rename = "totalSent")]
    pub total_sent: f64,
    /// Total emails delivered
    #[serde(rename = "totalDelivered")]
    pub total_delivered: f64,
    /// Total emails opened
    #[serde(rename = "totalOpened")]
    pub total_opened: f64,
    /// Total emails clicked
    #[serde(rename = "totalClicked")]
    pub total_clicked: f64,
    /// Total emails bounced
    #[serde(rename = "totalBounced")]
    pub total_bounced: f64,
    /// Total emails complained
    #[serde(rename = "totalComplained")]
    pub total_complained: f64,
    /// Delivery rate percentage
    #[serde(rename = "deliveryRate")]
    pub delivery_rate: f64,
    /// Open rate percentage
    #[serde(rename = "openRate")]
    pub open_rate: f64,
    /// Click rate percentage
    #[serde(rename = "clickRate")]
    pub click_rate: f64,
    /// Bounce rate percentage
    #[serde(rename = "bounceRate")]
    pub bounce_rate: f64,
    /// Complaint rate percentage
    #[serde(rename = "complaintRate")]
    pub complaint_rate: f64,
}

impl GetDomainStats200Response {
    pub fn new(total_sent: f64, total_delivered: f64, total_opened: f64, total_clicked: f64, total_bounced: f64, total_complained: f64, delivery_rate: f64, open_rate: f64, click_rate: f64, bounce_rate: f64, complaint_rate: f64) -> GetDomainStats200Response {
        GetDomainStats200Response {
            total_sent,
            total_delivered,
            total_opened,
            total_clicked,
            total_bounced,
            total_complained,
            delivery_rate,
            open_rate,
            click_rate,
            bounce_rate,
            complaint_rate,
        }
    }
}

// From: get_domains_200_response_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomains200ResponseInner {
    /// The ID of the domain
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the domain
    #[serde(rename = "name")]
    pub name: String,
    /// The ID of the team
    #[serde(rename = "teamId")]
    pub team_id: String,
    /// Whether auto-routing is enabled
    #[serde(rename = "autoRouting", skip_serializing_if = "Option::is_none")]
    pub auto_routing: Option<bool>,
    /// The provider routes for this domain
    #[serde(rename = "routes")]
    pub routes: Vec<GetDomains200ResponseInnerRoutesInner>,
    /// The creation date of the domain
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The last update date of the domain
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GetDomains200ResponseInner {
    pub fn new(id: String, name: String, team_id: String, routes: Vec<GetDomains200ResponseInnerRoutesInner>, created_at: String, updated_at: String) -> GetDomains200ResponseInner {
        GetDomains200ResponseInner {
            id,
            name,
            team_id,
            auto_routing: None,
            routes,
            created_at,
            updated_at,
        }
    }
}

// From: get_domains_200_response_inner_routes_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomains200ResponseInnerRoutesInner {
    /// The ID of the route
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the domain
    #[serde(rename = "domainId")]
    pub domain_id: String,
    /// The ID of the provider connection
    #[serde(rename = "providerConnectionId")]
    pub provider_connection_id: String,
    /// Relative routing weight
    #[serde(rename = "weight")]
    pub weight: i32,
    /// Whether the route is active
    #[serde(rename = "isActive")]
    pub is_active: bool,
    /// The status of the domain
    #[serde(rename = "status")]
    pub status: String,
    /// The email provider for this route
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// The region of the provider
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Whether click tracking is enabled
    #[serde(rename = "clickTracking", skip_serializing_if = "Option::is_none")]
    pub click_tracking: Option<bool>,
    /// Whether open tracking is enabled
    #[serde(rename = "openTracking", skip_serializing_if = "Option::is_none")]
    pub open_tracking: Option<bool>,
    /// The DKIM public key
    #[serde(rename = "publicKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Option<String>>,
    /// The DKIM verification status
    #[serde(rename = "dkimStatus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dkim_status: Option<Option<String>>,
    /// The SPF verification details
    #[serde(rename = "spfDetails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spf_details: Option<Option<String>>,
    /// Whether DMARC is added
    #[serde(rename = "dmarcAdded", skip_serializing_if = "Option::is_none")]
    pub dmarc_added: Option<bool>,
    /// Whether the route is being verified
    #[serde(rename = "isVerifying", skip_serializing_if = "Option::is_none")]
    pub is_verifying: Option<bool>,
    /// The verification error message
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    /// The subdomain
    #[serde(rename = "subdomain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subdomain: Option<Option<String>>,
    /// The DNS records for this route
    #[serde(rename = "dnsRecords")]
    pub dns_records: Vec<GetDomains200ResponseInnerRoutesInnerDnsRecordsInner>,
    /// The creation date
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The last update date
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GetDomains200ResponseInnerRoutesInner {
    pub fn new(id: String, domain_id: String, provider_connection_id: String, weight: i32, is_active: bool, status: String, provider: Provider, dns_records: Vec<GetDomains200ResponseInnerRoutesInnerDnsRecordsInner>, created_at: String, updated_at: String) -> GetDomains200ResponseInnerRoutesInner {
        GetDomains200ResponseInnerRoutesInner {
            id,
            domain_id,
            provider_connection_id,
            weight,
            is_active,
            status,
            provider,
            region: None,
            click_tracking: None,
            open_tracking: None,
            public_key: None,
            dkim_status: None,
            spf_details: None,
            dmarc_added: None,
            is_verifying: None,
            error_message: None,
            subdomain: None,
            dns_records,
            created_at,
            updated_at,
        }
    }
}

// From: get_domains_200_response_inner_routes_inner_dns_records_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDomains200ResponseInnerRoutesInnerDnsRecordsInner {
    /// DNS record type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// DNS record name
    #[serde(rename = "name")]
    pub name: String,
    /// DNS record value
    #[serde(rename = "value")]
    pub value: String,
    /// DNS record TTL
    #[serde(rename = "ttl")]
    pub ttl: String,
    /// DNS record priority
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<String>>,
    /// The status of the domain
    #[serde(rename = "status")]
    pub status: String,
    /// Whether the record is recommended
    #[serde(rename = "recommended", skip_serializing_if = "Option::is_none")]
    pub recommended: Option<bool>,
}

impl GetDomains200ResponseInnerRoutesInnerDnsRecordsInner {
    pub fn new(r#type: Type, name: String, value: String, ttl: String, status: String) -> GetDomains200ResponseInnerRoutesInnerDnsRecordsInner {
        GetDomains200ResponseInnerRoutesInnerDnsRecordsInner {
            r#type,
            name,
            value,
            ttl,
            priority: None,
            status,
            recommended: None,
        }
    }
}
/// DNS record type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MX")]
    Mx,
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "CNAME")]
    Cname,
}

impl Default for Type {
    fn default() -> Type {
        Self::Mx
    }
}

// From: get_health_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHealth200Response {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "uptime")]
    pub uptime: f64,
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
}

impl GetHealth200Response {
    pub fn new(status: String, uptime: f64, timestamp: f64) -> GetHealth200Response {
        GetHealth200Response {
            status,
            uptime,
            timestamp,
        }
    }
}

// From: get_settings_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSettings200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "dailyEmailLimit")]
    pub daily_email_limit: f64,
    #[serde(rename = "monthlyEmailLimit")]
    pub monthly_email_limit: f64,
}

impl GetSettings200Response {
    pub fn new(id: String, name: String, plan: String, daily_email_limit: f64, monthly_email_limit: f64) -> GetSettings200Response {
        GetSettings200Response {
            id,
            name,
            plan,
            daily_email_limit,
            monthly_email_limit,
        }
    }
}

// From: get_templates_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTemplates200Response {
    #[serde(rename = "data")]
    pub data: Vec<GetTemplates200ResponseDataInner>,
}

impl GetTemplates200Response {
    pub fn new(data: Vec<GetTemplates200ResponseDataInner>) -> GetTemplates200Response {
        GetTemplates200Response {
            data,
        }
    }
}

// From: get_templates_200_response_data_inner.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTemplates200ResponseDataInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "html", deserialize_with = "Option::deserialize")]
    pub html: Option<String>,
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl GetTemplates200ResponseDataInner {
    pub fn new(id: String, name: String, subject: String, html: Option<String>, content: Option<String>, team_id: String, created_at: String, updated_at: String) -> GetTemplates200ResponseDataInner {
        GetTemplates200ResponseDataInner {
            id,
            name,
            subject,
            html,
            content,
            team_id,
            created_at,
            updated_at,
        }
    }
}

// From: get_version_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVersion200Response {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<String>,
    #[serde(rename = "nodeVersion")]
    pub node_version: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "arch")]
    pub arch: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "versions")]
    pub versions: std::collections::HashMap<String, String>,
    #[serde(rename = "memory")]
    pub memory: Box<GetVersion200ResponseMemory>,
}

impl GetVersion200Response {
    pub fn new(version: String, node_version: String, platform: String, arch: String, timestamp: String, versions: std::collections::HashMap<String, String>, memory: GetVersion200ResponseMemory) -> GetVersion200Response {
        GetVersion200Response {
            version,
            environment: None,
            node_version,
            platform,
            arch,
            timestamp,
            versions,
            memory: Box::new(memory),
        }
    }
}

// From: get_version_200_response_memory.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVersion200ResponseMemory {
    #[serde(rename = "rss")]
    pub rss: f64,
    #[serde(rename = "heapTotal")]
    pub heap_total: f64,
    #[serde(rename = "heapUsed")]
    pub heap_used: f64,
    #[serde(rename = "external")]
    pub external: f64,
}

impl GetVersion200ResponseMemory {
    pub fn new(rss: f64, heap_total: f64, heap_used: f64, external: f64) -> GetVersion200ResponseMemory {
        GetVersion200ResponseMemory {
            rss,
            heap_total,
            heap_used,
            external,
        }
    }
}

// From: list_emails_domain_id_parameter.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEmailsDomainIdParameter {
}

impl ListEmailsDomainIdParameter {
    pub fn new() -> ListEmailsDomainIdParameter {
        ListEmailsDomainIdParameter {
        }
    }
}

// From: schedule_campaign_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleCampaignRequest {
    /// Timestamp in ISO 8601 format or natural language (e.g., 'tomorrow 9am', 'next monday 10:30')
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "batchSize", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i32>,
}

impl ScheduleCampaignRequest {
    pub fn new() -> ScheduleCampaignRequest {
        ScheduleCampaignRequest {
            scheduled_at: None,
            batch_size: None,
        }
    }
}

// From: send_email_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendEmailRequest {
    #[serde(rename = "to")]
    pub to: serde_json::Value,
    #[serde(rename = "from")]
    pub from: String,
    /// Optional when templateId is provided
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// ID of a template from the dashboard
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "replyTo", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<serde_json::Value>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<serde_json::Value>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<serde_json::Value>,
    #[serde(rename = "text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text: Option<Option<String>>,
    #[serde(rename = "html", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub html: Option<Option<String>>,
    /// Custom headers to included with the emails
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<serde_json::Value>>,
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "inReplyToId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_reply_to_id: Option<Option<String>>,
}

impl SendEmailRequest {
    pub fn new(to: serde_json::Value, from: String) -> SendEmailRequest {
        SendEmailRequest {
            to: to,
            from,
            subject: None,
            template_id: None,
            variables: None,
            reply_to: None,
            cc: None,
            bcc: None,
            text: None,
            html: None,
            headers: None,
            attachments: None,
            scheduled_at: None,
            in_reply_to_id: None,
        }
    }
}

// From: send_email_request_to.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendEmailRequestTo {
}

impl SendEmailRequestTo {
    pub fn new() -> SendEmailRequestTo {
        SendEmailRequestTo {
        }
    }
}

// From: success_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuccessResponse {
    #[serde(rename = "success")]
    pub success: bool,
}

impl SuccessResponse {
    pub fn new(success: bool) -> SuccessResponse {
        SuccessResponse {
            success,
        }
    }
}

// From: update_contact_book_200_response.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContactBook200Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateContactBook200Response {
    pub fn new(id: String, name: String) -> UpdateContactBook200Response {
        UpdateContactBook200Response {
            id,
            name,
        }
    }
}

// From: update_contact_book_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContactBookRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl UpdateContactBookRequest {
    pub fn new() -> UpdateContactBookRequest {
        UpdateContactBookRequest {
            name: None,
            emoji: None,
            properties: None,
        }
    }
}

// From: update_contact_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContactRequest {
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "subscribed", skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
}

impl UpdateContactRequest {
    pub fn new() -> UpdateContactRequest {
        UpdateContactRequest {
            first_name: None,
            last_name: None,
            properties: None,
            subscribed: None,
        }
    }
}

// From: update_domain_route_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDomainRouteRequest {
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(rename = "clickTracking", skip_serializing_if = "Option::is_none")]
    pub click_tracking: Option<bool>,
    #[serde(rename = "openTracking", skip_serializing_if = "Option::is_none")]
    pub open_tracking: Option<bool>,
}

impl UpdateDomainRouteRequest {
    pub fn new() -> UpdateDomainRouteRequest {
        UpdateDomainRouteRequest {
            weight: None,
            click_tracking: None,
            open_tracking: None,
        }
    }
}

// From: update_template_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTemplateRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl UpdateTemplateRequest {
    pub fn new() -> UpdateTemplateRequest {
        UpdateTemplateRequest {
            name: None,
            subject: None,
            html: None,
            content: None,
        }
    }
}

// From: update_webhook_request.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebhookRequest {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "eventTypes", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<EventTypes>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "rotateSecret", skip_serializing_if = "Option::is_none")]
    pub rotate_secret: Option<bool>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl UpdateWebhookRequest {
    pub fn new() -> UpdateWebhookRequest {
        UpdateWebhookRequest {
            url: None,
            description: None,
            event_types: None,
            active: None,
            rotate_secret: None,
            secret: None,
        }
    }
}

// From: webhook.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


/// Webhook : Webhook details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Webhook {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<EventTypes>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "apiVersion", deserialize_with = "Option::deserialize")]
    pub api_version: Option<String>,
    #[serde(rename = "consecutiveFailures")]
    pub consecutive_failures: f64,
    #[serde(rename = "lastSuccessAt", deserialize_with = "Option::deserialize")]
    pub last_success_at: Option<String>,
    #[serde(rename = "lastFailureAt", deserialize_with = "Option::deserialize")]
    pub last_failure_at: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "createdByUserId", deserialize_with = "Option::deserialize")]
    pub created_by_user_id: Option<String>,
}

impl Webhook {
    /// Webhook details
    pub fn new(id: String, url: String, description: Option<String>, event_types: Vec<EventTypes>, status: String, secret: String, api_version: Option<String>, consecutive_failures: f64, last_success_at: Option<String>, last_failure_at: Option<String>, created_at: String, updated_at: String, team_id: String, created_by_user_id: Option<String>) -> Webhook {
        Webhook {
            id,
            url,
            description,
            event_types,
            status,
            secret,
            api_version,
            consecutive_failures,
            last_success_at,
            last_failure_at,
            created_at,
            updated_at,
            team_id,
            created_by_user_id,
        }
    }
}

// From: webhook_call.rs
/*
 * Unsent API
 *
 * API for Unsent.dev
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@unsent.dev
 * Generated by: https://openapi-generator.tech
 */


/// WebhookCall : Webhook call details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCall {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "teamId")]
    pub team_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "webhookId")]
    pub webhook_id: String,
    #[serde(rename = "payload")]
    pub payload: String,
    #[serde(rename = "attempt")]
    pub attempt: f64,
    #[serde(rename = "nextAttemptAt", deserialize_with = "Option::deserialize")]
    pub next_attempt_at: Option<String>,
    #[serde(rename = "lastError", deserialize_with = "Option::deserialize")]
    pub last_error: Option<String>,
    #[serde(rename = "responseStatus", deserialize_with = "Option::deserialize")]
    pub response_status: Option<f64>,
    #[serde(rename = "responseTimeMs", deserialize_with = "Option::deserialize")]
    pub response_time_ms: Option<f64>,
    #[serde(rename = "responseText", deserialize_with = "Option::deserialize")]
    pub response_text: Option<String>,
}

impl WebhookCall {
    /// Webhook call details
    pub fn new(id: String, r#type: String, created_at: String, updated_at: String, team_id: String, status: String, webhook_id: String, payload: String, attempt: f64, next_attempt_at: Option<String>, last_error: Option<String>, response_status: Option<f64>, response_time_ms: Option<f64>, response_text: Option<String>) -> WebhookCall {
        WebhookCall {
            id,
            r#type,
            created_at,
            updated_at,
            team_id,
            status,
            webhook_id,
            payload,
            attempt,
            next_attempt_at,
            last_error,
            response_status,
            response_time_ms,
            response_text,
        }
    }
}

